### ISSUE TITLE
Allow for arbitrary data modalities

### ISSUE THREAD

**Issue by johanos1** [aidotse/LeakPro#54]
# Feature
## Desired Behavior / Functionality
Currently, it is assumed that data can be expressed as numpy arrays and indexed accordingly. This is not aligned with some data modalities, e.g., graph data or text. Arbitrary data modalities should be supported.

## What Needs to Be Done
Bring out the data handling to the user and read in a class that yield a dataloader when queried.

## How Can It Be Tested
- Try attacks
- Implement unit tests on different data modalities (graph, text, image)

**Comment by FabianKruger** [comment]
I've started working on the changes discussed in this issue and have shared the initial implementation here: [#63](https://github.com/aidotse/LeakPro/pull/63). This is just the beginning of the work, and it still requires bug fixes and further adaptations to the rest of the code. Feel free to adapt it in any way that is useful for the project.
