### ISSUE TITLE
Shadow_model_handler, training data not sampling from the correct indicies 

### ISSUE THREAD

**Issue by henrikfo** [aidotse/LeakPro#57]
# Issue
## Problem Description
In the file shadow_model_handler.py ( in the function create_shadow_models ) , when sampling data to be used for training shadowmodels, it will not sample the intended data. It can sample multiple forbidden indicies to use e.g. target train and test data when they are excluded from " attack_data_index "

## Expected Behavior
When sampling training data from shadow models, it can't use excluded indicies

## What Needs to be Done
Make the shadow_model_handler.create_shadow_model() replace the dataset argument "attack_data" with the list "attack_data_index" and  the dataset "population" and use these to sample the shadow model training data. 

## How Can It Be Tested or Reproduced
Use the "get_in_indices_mask" in shadow_model_handler and check that the offline attacks returns 0 True(s)
This indicates that the offline attack has 0 IN- samples. For any offline attack this should hold.

OR check that the indicies that is beeing sampled for "shadow_data_indices" is strictly a subsample of the allowed indicies ( e.g. not containing any target train and test indicies if the are to be excluded )

**Comment by johanos1** [comment]
Ok, we really need to start implementing Unit tests.
